import { ProductItem } from './types';

export const DEFAULT_MATERIALS: ProductItem[] = [
  // MDFs Brancos e Madeirados (padrão 2.75m x 1.85m = 5.09 m2)
  {
    id: 'mat-1',
    code: 'MDF-BRANCO-15',
    subcodes: ['MDF15BR', 'BRANCO15', '15BRANCO', 'MDF_BRANCO_15MM', 'CHAPA_MDF_15_BRANCO'],
    description: 'MDF Branco TX 15mm (2 Faces)',
    unit: 'M2',
    unit_price: 36.50,
    category: 'MDF',
  },
  {
    id: 'mat-2',
    code: 'MDF-BRANCO-18',
    subcodes: ['MDF18BR', 'BRANCO18', '18BRANCO', 'MDF_BRANCO_18MM'],
    description: 'MDF Branco TX 18mm (2 Faces)',
    unit: 'M2',
    unit_price: 43.80,
    category: 'MDF',
  },
  {
    id: 'mat-3',
    code: 'MDF-BRANCO-06',
    subcodes: ['MDF06BR', 'BRANCO06', 'MDF_BRANCO_6MM', 'FUNDO_06'],
    description: 'MDF Branco TX 6mm (Fundo)',
    unit: 'M2',
    unit_price: 22.00,
    category: 'MDF',
  },
  {
    id: 'mat-4',
    code: 'MDF-FREIJO-15',
    subcodes: ['FREIJO15', 'LOURO_FREIJO_15', 'MDF_FREIJO_15MM'],
    description: 'MDF Louro Freijó Arauco 15mm',
    unit: 'M2',
    unit_price: 64.00,
    category: 'MDF',
  },
  {
    id: 'mat-5',
    code: 'MDF-FREIJO-18',
    subcodes: ['FREIJO18', 'LOURO_FREIJO_18', 'MDF_FREIJO_18MM'],
    description: 'MDF Louro Freijó Arauco 18mm',
    unit: 'M2',
    unit_price: 76.50,
    category: 'MDF',
  },
  {
    id: 'mat-6',
    code: 'MDF-GRAFITE-15',
    subcodes: ['GRAFITE15', 'CINZA_GRAFITE_15'],
    description: 'MDF Grafite Trama Duratex 15mm',
    unit: 'M2',
    unit_price: 58.00,
    category: 'MDF',
  },
  // Fitas de Borda (Rolos de 20m ou 50m)
  {
    id: 'mat-7',
    code: 'FITA-BRANCA-22',
    subcodes: ['FITA_BORDA_BRANCA_22', 'FITABR22', 'BORDA_BRANCA_22X0.45'],
    description: 'Fita de Borda PVC Branco TX 22x0,45mm (Rolo 20m)',
    unit: 'UN',
    unit_price: 28.00,
    fita_metros: 20,
    category: 'FITA',
  },
  {
    id: 'mat-8',
    code: 'FITA-BRANCA-35',
    subcodes: ['FITA_BORDA_BRANCA_35', 'FITABR35', 'BORDA_BRANCA_35X0.45'],
    description: 'Fita de Borda PVC Branco TX 35x0,45mm (Rolo 20m)',
    unit: 'UN',
    unit_price: 42.00,
    fita_metros: 20,
    category: 'FITA',
  },
  {
    id: 'mat-9',
    code: 'FITA-FREIJO-22',
    subcodes: ['FITA_BORDA_FREIJO_22', 'BORDA_FREIJO_22'],
    description: 'Fita de Borda Louro Freijó 22x0,45mm (Rolo 20m)',
    unit: 'UN',
    unit_price: 46.00,
    fita_metros: 20,
    category: 'FITA',
  },
  // Ferragens e Acessórios
  {
    id: 'mat-10',
    code: 'CORREDICA-TELESC-45',
    subcodes: ['CORR_45', 'CORREDICA_450MM', 'TELESC_450'],
    description: 'Corrediça Telescópica Larga 450mm',
    unit: 'PAR',
    unit_price: 24.50,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-11',
    code: 'CORREDICA-TELESC-50',
    subcodes: ['CORR_50', 'CORREDICA_500MM', 'TELESC_500'],
    description: 'Corrediça Telescópica Larga 500mm',
    unit: 'PAR',
    unit_price: 27.00,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-12',
    code: 'DOBRADICA-AMORT-35',
    subcodes: ['DOBR_CURVA_AMORT', 'DOBRADICA_PISTAO_35', 'DOBR_RETA_AMORT'],
    description: 'Dobradiça Curva 35mm com Amortecedor Clip-on',
    unit: 'UN',
    unit_price: 7.90,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-13',
    code: 'PUXADOR-PERFIL-ALUM',
    subcodes: ['PUX_PERFIL', 'PERFIL_GOLA', 'PUXADOR_GOLA_METRO'],
    description: 'Puxador Perfil Alumínio Champagne (Barra 3m)',
    unit: 'UN',
    unit_price: 68.00,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-14',
    code: 'PISTAO-A-GAS-80N',
    subcodes: ['PISTAO_80N', 'AMORTECEDOR_PORTA_BASCULANTE'],
    description: 'Pistão a Gás Força 80N para Porta Basculante',
    unit: 'UN',
    unit_price: 14.50,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-15',
    code: 'PARAFUSO-4X40',
    subcodes: ['PARAFUSO_CHATO_4X40', 'PARAF_4X40'],
    description: 'Parafuso Chipboard Philips Chata 4,0x40mm (Cento)',
    unit: 'CENTO',
    unit_price: 11.00,
    category: 'FERRAGEM',
  },
  // Mão de Obra Fixa & Processos de Fabricação
  {
    id: 'mat-mo-1',
    code: 'PORTA-RETA',
    subcodes: ['PORTA RETA', 'PROCESSO DE FABRICAÇÃO', 'FAB_PORTA_RETA'],
    description: 'Processo de Fabricação - Porta Reta',
    unit: 'UN',
    unit_price: 70.00,
    category: 'MAO_DE_OBRA',
  },
  {
    id: 'mat-mo-2',
    code: 'PORTA-CAVA-HORIZ',
    subcodes: ['PORTA CAVA HORIZONTAL', 'PORTA CAVA', 'CAVA_HORIZONTAL'],
    description: 'Processo de Fabricação - Porta Cava Horizontal',
    unit: 'UN',
    unit_price: 70.00,
    category: 'MAO_DE_OBRA',
  },
  {
    id: 'mat-mo-3',
    code: 'FRENTE-CAVA-HORIZ',
    subcodes: ['FRENTE CAVA HORIZONTAL', 'FRENTE CAVA', 'CAVA_GAVETA'],
    description: 'Processo de Fabricação - Frente Cava Horizontal',
    unit: 'UN',
    unit_price: 70.00,
    category: 'MAO_DE_OBRA',
  },
  {
    id: 'mat-mo-4',
    code: 'PORTA-CAVA-45',
    subcodes: ['PORTA CAVA 45', 'CAVA 45', 'CAVA_45_GRAUS'],
    description: 'Processo de Fabricação - Porta Cava 45°',
    unit: 'UN',
    unit_price: 85.00,
    category: 'MAO_DE_OBRA',
  },
  {
    id: 'mat-mo-5',
    code: 'MONTAGEM-MODULO',
    subcodes: ['MONTAGEM MODULO', 'MONTAGEM BALCAO', 'MONTAGEM_ARMARIO'],
    description: 'Mão de Obra de Montagem e Ajuste de Módulo',
    unit: 'UN',
    unit_price: 60.00,
    category: 'MAO_DE_OBRA',
  }
];
