import { ProductItem } from './types';

export const DEFAULT_MATERIALS: ProductItem[] = [
  // ==========================================
  // 1. MDFs Brancos e Madeirados (padrão 2.75m x 1.85m = 5.09 m²) - Custo Base
  // ==========================================
  {
    id: 'mat-1',
    code: 'MDF-BRANCO-15',
    subcodes: ['MDF15BR', 'BRANCO15', '15BRANCO', 'MDF_BRANCO_15MM', 'CHAPA_MDF_15_BRANCO'],
    description: 'MDF Branco TX 15mm (2 Faces)',
    unit: 'M2',
    unit_price: 36.50,
    category: 'MDF',
  },
  {
    id: 'mat-2',
    code: 'MDF-BRANCO-18',
    subcodes: ['MDF18BR', 'BRANCO18', '18BRANCO', 'MDF_BRANCO_18MM'],
    description: 'MDF Branco TX 18mm (2 Faces)',
    unit: 'M2',
    unit_price: 43.80,
    category: 'MDF',
  },
  {
    id: 'mat-3',
    code: 'MDF-BRANCO-06',
    subcodes: ['MDF06BR', 'BRANCO06', 'MDF_BRANCO_6MM', 'FUNDO_06'],
    description: 'MDF Branco TX 6mm (Fundo)',
    unit: 'M2',
    unit_price: 22.00,
    category: 'MDF',
  },
  {
    id: 'mat-4',
    code: 'MDF-FREIJO-15',
    subcodes: ['FREIJO15', 'LOURO_FREIJO_15', 'MDF_FREIJO_15MM'],
    description: 'MDF Louro Freijó Arauco 15mm',
    unit: 'M2',
    unit_price: 64.00,
    category: 'MDF',
  },
  {
    id: 'mat-5',
    code: 'MDF-FREIJO-18',
    subcodes: ['FREIJO18', 'LOURO_FREIJO_18', 'MDF_FREIJO_18MM'],
    description: 'MDF Louro Freijó Arauco 18mm',
    unit: 'M2',
    unit_price: 76.50,
    category: 'MDF',
  },
  {
    id: 'mat-6',
    code: 'MDF-GRAFITE-15',
    subcodes: ['GRAFITE15', 'CINZA_GRAFITE_15'],
    description: 'MDF Grafite Trama Duratex 15mm',
    unit: 'M2',
    unit_price: 58.00,
    category: 'MDF',
  },

  // ==========================================
  // 2. Fitas de Borda PVC (Rolos de 20m ou 50m) - Custo Base
  // ==========================================
  {
    id: 'mat-7',
    code: 'FITA-BRANCA-22',
    subcodes: ['FITA_BORDA_BRANCA_22', 'FITABR22', 'BORDA_BRANCA_22x0.45'],
    description: 'Fita de Borda PVC Branco TX 22×0,45mm (Rolo 20m)',
    unit: 'UN',
    unit_price: 28.00,
    fita_metros: 20,
    category: 'FITA',
  },
  {
    id: 'mat-8',
    code: 'FITA-BRANCA-35',
    subcodes: ['FITA_BORDA_BRANCA_35', 'FITABR35', 'BORDA_BRANCA_35x0.45'],
    description: 'Fita de Borda PVC Branco TX 35×0,45mm (Rolo 20m)',
    unit: 'UN',
    unit_price: 42.00,
    fita_metros: 20,
    category: 'FITA',
  },
  {
    id: 'mat-9',
    code: 'FITA-FREIJO-22',
    subcodes: ['FITA_BORDA_FREIJO_22', 'BORDA_FREIJO_22'],
    description: 'Fita de Borda Louro Freijó 22×0,45mm (Rolo 20m)',
    unit: 'UN',
    unit_price: 46.00,
    fita_metros: 20,
    category: 'FITA',
  },

  // ==========================================
  // 3. Ferragens e Acessórios Gerais (Catálogo Geral)
  // Preço Final definido pelo Operador (inicia limpo / 0,00)
  // ==========================================
  {
    id: 'mat-10',
    code: 'CORREDICA-TELESC-45',
    subcodes: ['CORR_45', 'CORREDICA_450MM', 'TELESC_450'],
    description: 'Corrediça Telescópica Larga 450mm',
    unit: 'PAR',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-11',
    code: 'CORREDICA-TELESC-50',
    subcodes: ['CORR_50', 'CORREDICA_500MM', 'TELESC_500'],
    description: 'Corrediça Telescópica Larga 500mm',
    unit: 'PAR',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-12',
    code: 'DOBRADICA-AMORT-35',
    subcodes: ['DOBR_CURVA_AMORT', 'DOBRADICA_PISTAO_35', 'DOBR_RETA_AMORT'],
    description: 'Dobradiça Curva 35mm com Amortecedor Clip-on',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-13',
    code: 'PUXADOR-PERFIL-ALUM',
    subcodes: ['PUX_PERFIL', 'PERFIL_GOLA', 'PUXADOR_GOLA_METRO'],
    description: 'Puxador Perfil Alumínio Champagne (Barra 3m)',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-14',
    code: 'PISTAO-A-GAS-80N',
    subcodes: ['PISTAO_80N', 'AMORTECEDOR_PORTA_BASCULANTE'],
    description: 'Pistão a Gás Força 80N para Porta Basculante',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-15',
    code: 'PARAFUSO-4X40',
    subcodes: ['PARAFUSO_CHATO_4X40', 'PARAF_4X40'],
    description: 'Parafuso Chipboard Philips Chata 4,0x40mm (Cento)',
    unit: 'CENTO',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-16',
    code: 'DOBRADICA-RETA-AMORT',
    subcodes: ['DOBR_RETA_AMORT', 'DOBRADICA_RETA_AMORTECEDOR'],
    description: 'Dobradiça Reta com Amortecedor Clip-on',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-17',
    code: 'DOBRADICA-SEM-AMORT',
    subcodes: ['DOBR_SEM_AMORT', 'DOBRADICA_S_AMORT', 'DOBRADICA_BAIXA'],
    description: 'Dobradiça Aço s/ Amort. Reta / Baixa',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-18',
    code: 'DOBRADICA-CANTO-L-RETA',
    subcodes: ['DOBR_CANTO_L_RETA', 'DOBRADICA_CANTO_L_RETA'],
    description: 'Dobradiça reta canto L com amortecedor',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-19',
    code: 'DOBRADICA-CANTO-L-CURVA',
    subcodes: ['DOBR_CANTO_L_CURVA', 'DOBRADICA_CANTO_L'],
    description: 'Dobradiça Curva Canto L com amortecedor',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-20',
    code: 'CORREDICA-TELESC-30',
    subcodes: ['CORR_30', 'CORREDICA_300MM', 'TELESC_300'],
    description: 'Corrediça Telescópica 300mm',
    unit: 'PAR',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-21',
    code: 'CORREDICA-TELESC-35',
    subcodes: ['CORR_35', 'CORREDICA_350MM', 'TELESC_350'],
    description: 'Corrediça Telescópica 350mm',
    unit: 'PAR',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-22',
    code: 'CORREDICA-TELESC-40',
    subcodes: ['CORR_40', 'CORREDICA_400MM', 'TELESC_400'],
    description: 'Corrediça Telescópica 400mm',
    unit: 'PAR',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-23',
    code: 'CORREDICA-INV-35',
    subcodes: ['CORR_INV_350', 'INVISIVEL_350'],
    description: 'Corrediça invisível com freio 350mm',
    unit: 'PAR',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-24',
    code: 'CORREDICA-INV-40',
    subcodes: ['CORR_INV_400', 'INVISIVEL_400'],
    description: 'Corrediça invisível com freio 400mm',
    unit: 'PAR',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-25',
    code: 'CORREDICA-INV-45',
    subcodes: ['CORR_INV_450', 'INVISIVEL_450', 'CORR-INV'],
    description: 'Corrediça invisível com amortecedor 450mm',
    unit: 'PAR',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-26',
    code: 'CORREDICA-INV-50',
    subcodes: ['CORR_INV_500', 'INVISIVEL_500'],
    description: 'Corrediça invisível com freio 500mm',
    unit: 'PAR',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-27',
    code: 'PUXADOR-GOLA-3M',
    subcodes: ['PUX_GOLA', 'PUX_GOLA_3M', 'PERFIL_GOLA_3M', 'PUX-GOLA'],
    description: 'Puxador gola barra (3m)',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-28',
    code: 'PONTEIRA-GOLA',
    subcodes: ['PONTEIRA_GOLA'],
    description: 'Ponteira para Puxador Gola',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-29',
    code: 'PUXADOR-CONTINUO-3M',
    subcodes: ['PUX_CONTINUO', 'PERFIL_CONTINUO'],
    description: 'Puxador Contínuo Alumínio (Barra 3m)',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-30',
    code: 'PONTEIRA-CONTINUO',
    subcodes: ['PONTEIRA_CONTINUO'],
    description: 'Ponteira para Puxador Contínuo',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-31',
    code: 'PISTAO-A-GAS',
    subcodes: ['PISTAO_GAS', 'PISTAO_BASCULANTE', 'PIST-01'],
    description: 'Pistão a gás para porta basculante',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-32',
    code: 'PISTAO-GAS-INVERTIDO',
    subcodes: ['PISTAO_INVERTIDO'],
    description: 'Pistão a gás invertido',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-33',
    code: 'CABIDEIRO-CURVO',
    subcodes: ['CABIDEIRO_CURVO'],
    description: 'Cabideiro Curvo (1m x 1m)',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-34',
    code: 'CABIDEIRO-RETO-3M',
    subcodes: ['CABIDEIRO_RETO'],
    description: 'Cabideiro Reto (Barra 3m)',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-35',
    code: 'CABIDEIRO-EXTENSIVO',
    subcodes: ['CABIDEIRO_EXTENSIVO', 'CABIDEIRO_BASCULANTE'],
    description: 'Cabideiro extensivo articulado basculante',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-36',
    code: 'SUPORTE-CABIDEIRO',
    subcodes: ['SUPORTE_CABIDEIRO'],
    description: 'Suporte Lateral para Cabideiro Oval',
    unit: 'PAR',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-37',
    code: 'SISTEMA-CORRER-FREIO',
    subcodes: ['SISTEMA_CORRER', 'PORTA_CORRER_FREIO'],
    description: 'Sistema de correr com freio / amortecedor',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-38',
    code: 'TABUA-PASSAR-EMBUTIDA',
    subcodes: ['TABUA_PASSAR', 'TABUA_EMBUTIDA'],
    description: 'Tábua de passar embutida dobrável',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-39',
    code: 'GANCHO-VASSOURA',
    subcodes: ['GANCHO_VASSOURA', 'SUPORTE_VASSOURA'],
    description: 'Ganchos / suporte para vassoura',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-40',
    code: 'SUPORTE-MAO-FRANCESA',
    subcodes: ['MAO_FRANCESA'],
    description: 'Suporte Mão Francesa reforçada',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-41',
    code: 'RODIZIO-MAIOR-FREIO',
    subcodes: ['RODIZIO_FREIO'],
    description: 'Rodízio maior giratório com freio',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-42',
    code: 'RODIZIO-MAIOR-SEM-FREIO',
    subcodes: ['RODIZIO_SEM_FREIO'],
    description: 'Rodízio maior giratório sem freio',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-43',
    code: 'LIXEIRA-EMBUTIDA',
    subcodes: ['LIXEIRA_EMBUTIDA', 'LIXEIRA_INOX'],
    description: 'Lixeira embutida de inox',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-44',
    code: 'TOALHEIRO-EXTENSIVEL',
    subcodes: ['TOALHEIRO'],
    description: 'Toalheiro extensível',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-45',
    code: 'DIVISOR-GAVETA-ECO-30',
    subcodes: ['DIVISOR_ECOPLAST_300'],
    description: 'Divisor de gaveta ecoplast 300mm',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-46',
    code: 'DIVISOR-GAVETA-ECO-40',
    subcodes: ['DIVISOR_ECOPLAST_400'],
    description: 'Divisor de gaveta ecoplast 400mm',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-47',
    code: 'DIVISOR-GAVETA-ECO-50',
    subcodes: ['DIVISOR_ECOPLAST_500'],
    description: 'Divisor de gaveta ecoplast 500mm',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-48',
    code: 'DIVISOR-GAVETA-ECO-60',
    subcodes: ['DIVISOR_ECOPLAST_600'],
    description: 'Divisor de gaveta ecoplast 600mm',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-49',
    code: 'PORTA-GRAVATA-ACRILICO',
    subcodes: ['PORTA_GRAVATA'],
    description: 'Porta gravata acrílico',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },
  {
    id: 'mat-50',
    code: 'DIVISOR-ACRILICO',
    subcodes: ['DIVISOR_ACRILICO'],
    description: 'Divisor de acrílico para gaveta',
    unit: 'UN',
    unit_price: 0,
    category: 'FERRAGEM',
  },

  // ==========================================
  // 4. Mão de Obra Fixa & Processos de Fabricação
  // ==========================================
  {
    id: 'mat-mo-1',
    code: 'PORTA-RETA',
    subcodes: ['PORTA RETA', 'PROCESSO DE FABRICAÇÃO', 'FAB_PORTA_RETA'],
    description: 'Processo de Fabricação - Porta Reta',
    unit: 'UN',
    unit_price: 70.00,
    category: 'MAO_DE_OBRA',
  },
  {
    id: 'mat-mo-2',
    code: 'PORTA-CAVA-HORIZ',
    subcodes: ['PORTA CAVA HORIZONTAL', 'PORTA CAVA', 'CAVA_HORIZONTAL'],
    description: 'Processo de Fabricação - Porta Cava Horizontal',
    unit: 'UN',
    unit_price: 70.00,
    category: 'MAO_DE_OBRA',
  },
  {
    id: 'mat-mo-3',
    code: 'FRENTE-CAVA-HORIZ',
    subcodes: ['FRENTE CAVA HORIZONTAL', 'FRENTE CAVA', 'CAVA_GAVETA'],
    description: 'Processo de Fabricação - Frente Cava Horizontal',
    unit: 'UN',
    unit_price: 70.00,
    category: 'MAO_DE_OBRA',
  },
  {
    id: 'mat-mo-4',
    code: 'PORTA-CAVA-45',
    subcodes: ['PORTA CAVA 45', 'CAVA 45', 'CAVA_45_GRAUS'],
    description: 'Processo de Fabricação - Porta Cava 45°',
    unit: 'UN',
    unit_price: 85.00,
    category: 'MAO_DE_OBRA',
  },
  {
    id: 'mat-mo-5',
    code: 'MONTAGEM-MODULO',
    subcodes: ['MONTAGEM MODULO', 'MONTAGEM BALCAO', 'MONTAGEM_ARMARIO'],
    description: 'Mão de Obra de Montagem e Ajuste de Módulo',
    unit: 'UN',
    unit_price: 60.00,
    category: 'MAO_DE_OBRA',
  },
];
