/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as DashboardAgendaRouteImport } from './routes/_dashboard/agenda'
import { Route as DashboardDemandasRouteImport } from './routes/_dashboard/demandas'
import { Route as DashboardOrcamentoRouteImport } from './routes/_dashboard/orcamento'
import { Route as DashboardAdminComissoesRouteImport } from './routes/_dashboard/admin/comissoes'
import { Route as DashboardAdminCrmRouteImport } from './routes/_dashboard/admin/crm'
import { Route as DashboardAdminDashboardRouteImport } from './routes/_dashboard/admin/dashboard'
import { Route as DashboardAdminDriveRouteImport } from './routes/_dashboard/admin/drive'
import { Route as DashboardAdminEquipeRouteImport } from './routes/_dashboard/admin/equipe'
import { Route as DashboardProjetistaClientesRouteImport } from './routes/_dashboard/projetista/clientes'
import { Route as DashboardProjetistaDashboardRouteImport } from './routes/_dashboard/projetista/dashboard'
import { Route as DashboardProjetistaMeusProjetosRouteImport } from './routes/_dashboard/projetista/meus-projetos'
import { Route as DashboardProjetistaPerfilRouteImport } from './routes/_dashboard/projetista/perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDemandasRoute = DashboardDemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrcamentoRoute = DashboardOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminComissoesRoute = DashboardAdminComissoesRouteImport.update({
  id: '/admin/comissoes',
  path: '/admin/comissoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminCrmRoute = DashboardAdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminDashboardRoute = DashboardAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminDriveRoute = DashboardAdminDriveRouteImport.update({
  id: '/admin/drive',
  path: '/admin/drive',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminEquipeRoute = DashboardAdminEquipeRouteImport.update({
  id: '/admin/equipe',
  path: '/admin/equipe',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjetistaClientesRoute =
  DashboardProjetistaClientesRouteImport.update({
    id: '/projetista/clientes',
    path: '/projetista/clientes',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjetistaDashboardRoute =
  DashboardProjetistaDashboardRouteImport.update({
    id: '/projetista/dashboard',
    path: '/projetista/dashboard',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjetistaMeusProjetosRoute =
  DashboardProjetistaMeusProjetosRouteImport.update({
    id: '/projetista/meus-projetos',
    path: '/projetista/meus-projetos',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjetistaPerfilRoute =
  DashboardProjetistaPerfilRouteImport.update({
    id: '/projetista/perfil',
    path: '/projetista/perfil',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/agenda': typeof DashboardAgendaRoute
  '/demandas': typeof DashboardDemandasRoute
  '/orcamento': typeof DashboardOrcamentoRoute
  '/admin/comissoes': typeof DashboardAdminComissoesRoute
  '/admin/crm': typeof DashboardAdminCrmRoute
  '/admin/dashboard': typeof DashboardAdminDashboardRoute
  '/admin/drive': typeof DashboardAdminDriveRoute
  '/admin/equipe': typeof DashboardAdminEquipeRoute
  '/projetista/clientes': typeof DashboardProjetistaClientesRoute
  '/projetista/dashboard': typeof DashboardProjetistaDashboardRoute
  '/projetista/meus-projetos': typeof DashboardProjetistaMeusProjetosRoute
  '/projetista/perfil': typeof DashboardProjetistaPerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/agenda': typeof DashboardAgendaRoute
  '/demandas': typeof DashboardDemandasRoute
  '/orcamento': typeof DashboardOrcamentoRoute
  '/admin/comissoes': typeof DashboardAdminComissoesRoute
  '/admin/crm': typeof DashboardAdminCrmRoute
  '/admin/dashboard': typeof DashboardAdminDashboardRoute
  '/admin/drive': typeof DashboardAdminDriveRoute
  '/admin/equipe': typeof DashboardAdminEquipeRoute
  '/projetista/clientes': typeof DashboardProjetistaClientesRoute
  '/projetista/dashboard': typeof DashboardProjetistaDashboardRoute
  '/projetista/meus-projetos': typeof DashboardProjetistaMeusProjetosRoute
  '/projetista/perfil': typeof DashboardProjetistaPerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_dashboard/agenda': typeof DashboardAgendaRoute
  '/_dashboard/demandas': typeof DashboardDemandasRoute
  '/_dashboard/orcamento': typeof DashboardOrcamentoRoute
  '/_dashboard/admin/comissoes': typeof DashboardAdminComissoesRoute
  '/_dashboard/admin/crm': typeof DashboardAdminCrmRoute
  '/_dashboard/admin/dashboard': typeof DashboardAdminDashboardRoute
  '/_dashboard/admin/drive': typeof DashboardAdminDriveRoute
  '/_dashboard/admin/equipe': typeof DashboardAdminEquipeRoute
  '/_dashboard/projetista/clientes': typeof DashboardProjetistaClientesRoute
  '/_dashboard/projetista/dashboard': typeof DashboardProjetistaDashboardRoute
  '/_dashboard/projetista/meus-projetos': typeof DashboardProjetistaMeusProjetosRoute
  '/_dashboard/projetista/perfil': typeof DashboardProjetistaPerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando-aprovacao'
    | '/cadastro'
    | '/login'
    | '/redefinir-senha'
    | '/agenda'
    | '/demandas'
    | '/orcamento'
    | '/admin/comissoes'
    | '/admin/crm'
    | '/admin/dashboard'
    | '/admin/drive'
    | '/admin/equipe'
    | '/projetista/clientes'
    | '/projetista/dashboard'
    | '/projetista/meus-projetos'
    | '/projetista/perfil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando-aprovacao'
    | '/cadastro'
    | '/login'
    | '/redefinir-senha'
    | '/agenda'
    | '/demandas'
    | '/orcamento'
    | '/admin/comissoes'
    | '/admin/crm'
    | '/admin/dashboard'
    | '/admin/drive'
    | '/admin/equipe'
    | '/projetista/clientes'
    | '/projetista/dashboard'
    | '/projetista/meus-projetos'
    | '/projetista/perfil'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/aguardando-aprovacao'
    | '/cadastro'
    | '/login'
    | '/redefinir-senha'
    | '/_dashboard/agenda'
    | '/_dashboard/demandas'
    | '/_dashboard/orcamento'
    | '/_dashboard/admin/comissoes'
    | '/_dashboard/admin/crm'
    | '/_dashboard/admin/dashboard'
    | '/_dashboard/admin/drive'
    | '/_dashboard/admin/equipe'
    | '/_dashboard/projetista/clientes'
    | '/_dashboard/projetista/dashboard'
    | '/_dashboard/projetista/meus-projetos'
    | '/_dashboard/projetista/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/agenda': {
      id: '/_dashboard/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/demandas': {
      id: '/_dashboard/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof DashboardDemandasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/orcamento': {
      id: '/_dashboard/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof DashboardOrcamentoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/comissoes': {
      id: '/_dashboard/admin/comissoes'
      path: '/admin/comissoes'
      fullPath: '/admin/comissoes'
      preLoaderRoute: typeof DashboardAdminComissoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/crm': {
      id: '/_dashboard/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof DashboardAdminCrmRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/dashboard': {
      id: '/_dashboard/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof DashboardAdminDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/drive': {
      id: '/_dashboard/admin/drive'
      path: '/admin/drive'
      fullPath: '/admin/drive'
      preLoaderRoute: typeof DashboardAdminDriveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/equipe': {
      id: '/_dashboard/admin/equipe'
      path: '/admin/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof DashboardAdminEquipeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projetista/clientes': {
      id: '/_dashboard/projetista/clientes'
      path: '/projetista/clientes'
      fullPath: '/projetista/clientes'
      preLoaderRoute: typeof DashboardProjetistaClientesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projetista/dashboard': {
      id: '/_dashboard/projetista/dashboard'
      path: '/projetista/dashboard'
      fullPath: '/projetista/dashboard'
      preLoaderRoute: typeof DashboardProjetistaDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projetista/meus-projetos': {
      id: '/_dashboard/projetista/meus-projetos'
      path: '/projetista/meus-projetos'
      fullPath: '/projetista/meus-projetos'
      preLoaderRoute: typeof DashboardProjetistaMeusProjetosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projetista/perfil': {
      id: '/_dashboard/projetista/perfil'
      path: '/projetista/perfil'
      fullPath: '/projetista/perfil'
      preLoaderRoute: typeof DashboardProjetistaPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardDemandasRoute: typeof DashboardDemandasRoute
  DashboardOrcamentoRoute: typeof DashboardOrcamentoRoute
  DashboardAdminComissoesRoute: typeof DashboardAdminComissoesRoute
  DashboardAdminCrmRoute: typeof DashboardAdminCrmRoute
  DashboardAdminDashboardRoute: typeof DashboardAdminDashboardRoute
  DashboardAdminDriveRoute: typeof DashboardAdminDriveRoute
  DashboardAdminEquipeRoute: typeof DashboardAdminEquipeRoute
  DashboardProjetistaClientesRoute: typeof DashboardProjetistaClientesRoute
  DashboardProjetistaDashboardRoute: typeof DashboardProjetistaDashboardRoute
  DashboardProjetistaMeusProjetosRoute: typeof DashboardProjetistaMeusProjetosRoute
  DashboardProjetistaPerfilRoute: typeof DashboardProjetistaPerfilRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardDemandasRoute: DashboardDemandasRoute,
  DashboardOrcamentoRoute: DashboardOrcamentoRoute,
  DashboardAdminComissoesRoute: DashboardAdminComissoesRoute,
  DashboardAdminCrmRoute: DashboardAdminCrmRoute,
  DashboardAdminDashboardRoute: DashboardAdminDashboardRoute,
  DashboardAdminDriveRoute: DashboardAdminDriveRoute,
  DashboardAdminEquipeRoute: DashboardAdminEquipeRoute,
  DashboardProjetistaClientesRoute: DashboardProjetistaClientesRoute,
  DashboardProjetistaDashboardRoute: DashboardProjetistaDashboardRoute,
  DashboardProjetistaMeusProjetosRoute: DashboardProjetistaMeusProjetosRoute,
  DashboardProjetistaPerfilRoute: DashboardProjetistaPerfilRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
